"""
26 Canadian law firms tracked by the expansion tracker.
Each entry has:
  id          — short snake_case key used in CLI and DB
  name        — full legal name
  short       — abbreviated name used in signals
  website     — root URL for website scraper
  careers_url — direct link to careers/jobs page
  news_url    — press release / news page
  linkedin_slug — for future LinkedIn scraping
  tier        — 1=Bay Street elite, 2=national, 3=regional
  hq          — headquarters city
"""

FIRMS = [
    # ── Tier 1: Bay Street Elite ──────────────────────────────────────────
    {
        "id": "davies",
        "name": "Davies Ward Phillips & Vineberg LLP",
        "short": "Davies",
        "website": "https://www.dwpv.com",
        "careers_url": "https://www.dwpv.com/en/careers",
        "news_url": "https://www.dwpv.com/en/insights/news",
        "linkedin_slug": "davies-ward-phillips-vineberg",
        "tier": 1,
        "hq": "Toronto",
    },
    {
        "id": "blakes",
        "name": "Blake, Cassels & Graydon LLP",
        "short": "Blakes",
        "website": "https://www.blakes.com",
        "careers_url": "https://www.blakes.com/careers",
        "news_url": "https://www.blakes.com/insights/news",
        "linkedin_slug": "blake-cassels-graydon",
        "tier": 1,
        "hq": "Toronto",
    },
    {
        "id": "mccarthy",
        "name": "McCarthy Tétrault LLP",
        "short": "McCarthy",
        "website": "https://www.mccarthy.ca",
        "careers_url": "https://www.mccarthy.ca/en/careers",
        "news_url": "https://www.mccarthy.ca/en/insights/news",
        "linkedin_slug": "mccarthy-tetrault",
        "tier": 1,
        "hq": "Toronto",
    },
    {
        "id": "osler",
        "name": "Osler, Hoskin & Harcourt LLP",
        "short": "Osler",
        "website": "https://www.osler.com",
        "careers_url": "https://www.osler.com/en/careers",
        "news_url": "https://www.osler.com/en/resources/regulations/",
        "linkedin_slug": "osler-hoskin-harcourt",
        "tier": 1,
        "hq": "Toronto",
    },
    {
        "id": "stikeman",
        "name": "Stikeman Elliott LLP",
        "short": "Stikeman",
        "website": "https://www.stikeman.com",
        "careers_url": "https://www.stikeman.com/en-ca/careers",
        "news_url": "https://www.stikeman.com/en-ca/kh/all",
        "linkedin_slug": "stikeman-elliott",
        "tier": 1,
        "hq": "Montreal",
    },
    {
        "id": "torys",
        "name": "Torys LLP",
        "short": "Torys",
        "website": "https://www.torys.com",
        "careers_url": "https://www.torys.com/careers",
        "news_url": "https://www.torys.com/our-work/news",
        "linkedin_slug": "torys-llp",
        "tier": 1,
        "hq": "Toronto",
    },
    {
        "id": "goodmans",
        "name": "Goodmans LLP",
        "short": "Goodmans",
        "website": "https://www.goodmans.ca",
        "careers_url": "https://www.goodmans.ca/careers",
        "news_url": "https://www.goodmans.ca/news",
        "linkedin_slug": "goodmans-llp",
        "tier": 1,
        "hq": "Toronto",
    },
    # ── Tier 2: National Full-Service ─────────────────────────────────────
    {
        "id": "blg",
        "name": "Borden Ladner Gervais LLP",
        "short": "BLG",
        "website": "https://www.blg.com",
        "careers_url": "https://www.blg.com/en/careers",
        "news_url": "https://www.blg.com/en/insights",
        "linkedin_slug": "borden-ladner-gervais",
        "tier": 2,
        "hq": "Toronto",
    },
    {
        "id": "fasken",
        "name": "Fasken Martineau DuMoulin LLP",
        "short": "Fasken",
        "website": "https://www.fasken.com",
        "careers_url": "https://www.fasken.com/en/careers",
        "news_url": "https://www.fasken.com/en/knowledge",
        "linkedin_slug": "fasken",
        "tier": 2,
        "hq": "Toronto",
    },
    {
        "id": "bennett_jones",
        "name": "Bennett Jones LLP",
        "short": "Bennett Jones",
        "website": "https://www.bennettjones.com",
        "careers_url": "https://www.bennettjones.com/Careers",
        "news_url": "https://www.bennettjones.com/Publications",
        "linkedin_slug": "bennett-jones",
        "tier": 2,
        "hq": "Calgary",
    },
    {
        "id": "nrf",
        "name": "Norton Rose Fulbright Canada LLP",
        "short": "NRF",
        "website": "https://www.nortonrosefulbright.com/en-ca",
        "careers_url": "https://www.nortonrosefulbright.com/en-ca/careers",
        "news_url": "https://www.nortonrosefulbright.com/en-ca/knowledge",
        "linkedin_slug": "norton-rose-fulbright",
        "tier": 2,
        "hq": "Toronto",
    },
    {
        "id": "dentons",
        "name": "Dentons Canada LLP",
        "short": "Dentons",
        "website": "https://www.dentons.com/en/about-dentons/offices/canada",
        "careers_url": "https://www.dentons.com/en/careers",
        "news_url": "https://www.dentons.com/en/insights",
        "linkedin_slug": "dentons",
        "tier": 2,
        "hq": "Toronto",
    },
    {
        "id": "cassels",
        "name": "Cassels Brock & Blackwell LLP",
        "short": "Cassels",
        "website": "https://www.cassels.com",
        "careers_url": "https://www.cassels.com/careers/",
        "news_url": "https://www.cassels.com/publications/",
        "linkedin_slug": "cassels-brock-blackwell",
        "tier": 2,
        "hq": "Toronto",
    },
    {
        "id": "mcmillan",
        "name": "McMillan LLP",
        "short": "McMillan",
        "website": "https://mcmillan.ca",
        "careers_url": "https://mcmillan.ca/careers/",
        "news_url": "https://mcmillan.ca/insights/",
        "linkedin_slug": "mcmillan-llp",
        "tier": 2,
        "hq": "Toronto",
    },
    {
        "id": "gowling",
        "name": "Gowling WLG (Canada) LLP",
        "short": "Gowling WLG",
        "website": "https://gowling.com/en/canada/",
        "careers_url": "https://gowling.com/en/canada/careers/",
        "news_url": "https://gowling.com/en/canada/insights/",
        "linkedin_slug": "gowling-wlg",
        "tier": 2,
        "hq": "Ottawa",
    },
    # ── Tier 3: Regional ──────────────────────────────────────────────────
    {
        "id": "aird_berlis",
        "name": "Aird & Berlis LLP",
        "short": "Aird & Berlis",
        "website": "https://www.airdberlis.com",
        "careers_url": "https://www.airdberlis.com/careers",
        "news_url": "https://www.airdberlis.com/insights",
        "linkedin_slug": "aird-berlis",
        "tier": 3,
        "hq": "Toronto",
    },
    {
        "id": "miller_thomson",
        "name": "Miller Thomson LLP",
        "short": "Miller Thomson",
        "website": "https://www.millerthomson.com",
        "careers_url": "https://www.millerthomson.com/careers/",
        "news_url": "https://www.millerthomson.com/insights/",
        "linkedin_slug": "miller-thomson",
        "tier": 3,
        "hq": "Toronto",
    },
    {
        "id": "fogler",
        "name": "Fogler, Rubinoff LLP",
        "short": "Fogler",
        "website": "https://foglers.com",
        "careers_url": "https://foglers.com/careers/",
        "news_url": "https://foglers.com/news/",
        "linkedin_slug": "fogler-rubinoff",
        "tier": 3,
        "hq": "Toronto",
    },
    {
        "id": "weirfoulds",
        "name": "WeirFoulds LLP",
        "short": "WeirFoulds",
        "website": "https://www.weirfoulds.com",
        "careers_url": "https://www.weirfoulds.com/careers",
        "news_url": "https://www.weirfoulds.com/news",
        "linkedin_slug": "weirfoulds-llp",
        "tier": 3,
        "hq": "Toronto",
    },
    {
        "id": "torkin_manes",
        "name": "Torkin Manes LLP",
        "short": "Torkin Manes",
        "website": "https://www.torkinmanes.com",
        "careers_url": "https://www.torkinmanes.com/careers/",
        "news_url": "https://www.torkinmanes.com/our-thinking/",
        "linkedin_slug": "torkin-manes",
        "tier": 3,
        "hq": "Toronto",
    },
    {
        "id": "loopstra",
        "name": "Loopstra Nixon LLP",
        "short": "Loopstra Nixon",
        "website": "https://www.loopstranixon.com",
        "careers_url": "https://www.loopstranixon.com/careers/",
        "news_url": "https://www.loopstranixon.com/news/",
        "linkedin_slug": "loopstra-nixon",
        "tier": 3,
        "hq": "Toronto",
    },
    {
        "id": "minden_gross",
        "name": "Minden Gross LLP",
        "short": "Minden Gross",
        "website": "https://www.mindengross.com",
        "careers_url": "https://www.mindengross.com/careers/",
        "news_url": "https://www.mindengross.com/insights/",
        "linkedin_slug": "minden-gross",
        "tier": 3,
        "hq": "Toronto",
    },
    {
        "id": "bdp",
        "name": "Burnet, Duckworth & Palmer LLP",
        "short": "BD&P",
        "website": "https://www.bdplaw.com",
        "careers_url": "https://www.bdplaw.com/careers/",
        "news_url": "https://www.bdplaw.com/news/",
        "linkedin_slug": "burnet-duckworth-palmer",
        "tier": 3,
        "hq": "Calgary",
    },
    {
        "id": "lawson_lundell",
        "name": "Lawson Lundell LLP",
        "short": "Lawson Lundell",
        "website": "https://www.lawsonlundell.com",
        "careers_url": "https://www.lawsonlundell.com/careers/",
        "news_url": "https://www.lawsonlundell.com/publications/",
        "linkedin_slug": "lawson-lundell",
        "tier": 3,
        "hq": "Vancouver",
    },
    {
        "id": "mcinnes_cooper",
        "name": "McInnes Cooper",
        "short": "McInnes Cooper",
        "website": "https://www.mcinnescooper.com",
        "careers_url": "https://www.mcinnescooper.com/careers/",
        "news_url": "https://www.mcinnescooper.com/publications/",
        "linkedin_slug": "mcinnes-cooper",
        "tier": 3,
        "hq": "Halifax",
    },
    {
        "id": "stewart_mckelvey",
        "name": "Stewart McKelvey",
        "short": "Stewart McKelvey",
        "website": "https://www.stewartmckelvey.com",
        "careers_url": "https://www.stewartmckelvey.com/careers/",
        "news_url": "https://www.stewartmckelvey.com/insights/",
        "linkedin_slug": "stewart-mckelvey",
        "tier": 3,
        "hq": "Halifax",
    },
]

# Lookup helpers
FIRMS_BY_ID   = {f["id"]: f for f in FIRMS}
FIRMS_BY_SHORT = {f["short"].lower(): f for f in FIRMS}
