"""
Master list of 26 tracked Canadian law firms.
Each entry includes every URL variant scrapers need.
"""

FIRMS = [
    # ── TIER 1 — National full-service ──────────────────────────────────
    {
        "id": "davies",
        "name": "Davies Ward Phillips & Vineberg LLP",
        "short": "Davies",
        "website": "https://www.dwpv.com",
        "careers_url": "https://www.dwpv.com/en/careers",
        "news_url": "https://www.dwpv.com/en/insights/news",
        "linkedin_slug": "davies-ward-phillips-vineberg",
        "hq": "Toronto",
        "alt_names": ["Davies Ward", "DWPV"],
    },
    {
        "id": "blakes",
        "name": "Blake, Cassels & Graydon LLP",
        "short": "Blakes",
        "website": "https://www.blakes.com",
        "careers_url": "https://www.blakes.com/careers",
        "news_url": "https://www.blakes.com/insights",
        "linkedin_slug": "blake-cassels-graydon-llp",
        "hq": "Toronto",
        "alt_names": ["Blake Cassels", "Blakes"],
    },
    {
        "id": "mccarthy",
        "name": "McCarthy Tétrault LLP",
        "short": "McCarthy",
        "website": "https://www.mccarthy.ca",
        "careers_url": "https://www.mccarthy.ca/en/careers",
        "news_url": "https://www.mccarthy.ca/en/insights/news",
        "linkedin_slug": "mccarthy-tetrault",
        "hq": "Toronto",
        "alt_names": ["McCarthy Tetrault", "MT"],
    },
    {
        "id": "osler",
        "name": "Osler, Hoskin & Harcourt LLP",
        "short": "Osler",
        "website": "https://www.osler.com",
        "careers_url": "https://www.osler.com/en/careers",
        "news_url": "https://www.osler.com/en/resources/news",
        "linkedin_slug": "osler-hoskin-harcourt-llp",
        "hq": "Toronto",
        "alt_names": ["Osler Hoskin", "OHH"],
    },
    {
        "id": "stikeman",
        "name": "Stikeman Elliott LLP",
        "short": "Stikeman",
        "website": "https://www.stikeman.com",
        "careers_url": "https://www.stikeman.com/en-ca/careers",
        "news_url": "https://www.stikeman.com/en-ca/kh/all",
        "linkedin_slug": "stikeman-elliott",
        "hq": "Toronto",
        "alt_names": ["Stikeman"],
    },
    {
        "id": "torys",
        "name": "Torys LLP",
        "short": "Torys",
        "website": "https://www.torys.com",
        "careers_url": "https://www.torys.com/careers",
        "news_url": "https://www.torys.com/insights",
        "linkedin_slug": "torys-llp",
        "hq": "Toronto",
        "alt_names": ["Torys"],
    },
    {
        "id": "goodmans",
        "name": "Goodmans LLP",
        "short": "Goodmans",
        "website": "https://www.goodmans.ca",
        "careers_url": "https://www.goodmans.ca/careers",
        "news_url": "https://www.goodmans.ca/insights",
        "linkedin_slug": "goodmans-llp",
        "hq": "Toronto",
        "alt_names": ["Goodmans"],
    },
    # ── TIER 2 — Large national ──────────────────────────────────────────
    {
        "id": "blg",
        "name": "Borden Ladner Gervais LLP",
        "short": "BLG",
        "website": "https://www.blg.com",
        "careers_url": "https://www.blg.com/en/careers",
        "news_url": "https://www.blg.com/en/insights",
        "linkedin_slug": "borden-ladner-gervais",
        "hq": "Toronto",
        "alt_names": ["Borden Ladner", "BLG"],
    },
    {
        "id": "fasken",
        "name": "Fasken Martineau DuMoulin LLP",
        "short": "Fasken",
        "website": "https://www.fasken.com",
        "careers_url": "https://www.fasken.com/en/careers",
        "news_url": "https://www.fasken.com/en/knowledge",
        "linkedin_slug": "fasken",
        "hq": "Toronto",
        "alt_names": ["Fasken", "FMD"],
    },
    {
        "id": "bennett",
        "name": "Bennett Jones LLP",
        "short": "Bennett Jones",
        "website": "https://www.bennettjones.com",
        "careers_url": "https://www.bennettjones.com/careers",
        "news_url": "https://www.bennettjones.com/insights",
        "linkedin_slug": "bennett-jones-llp",
        "hq": "Calgary",
        "alt_names": ["Bennett Jones", "BJ"],
    },
    {
        "id": "nrf",
        "name": "Norton Rose Fulbright Canada LLP",
        "short": "NRF",
        "website": "https://www.nortonrosefulbright.com/en-ca",
        "careers_url": "https://www.nortonrosefulbright.com/en-ca/careers",
        "news_url": "https://www.nortonrosefulbright.com/en-ca/knowledge",
        "linkedin_slug": "norton-rose-fulbright",
        "hq": "Toronto",
        "alt_names": ["Norton Rose", "NRF"],
    },
    {
        "id": "dentons",
        "name": "Dentons Canada LLP",
        "short": "Dentons",
        "website": "https://www.dentons.com/en/find-your-dentons-team/offices/canada",
        "careers_url": "https://www.dentons.com/en/careers",
        "news_url": "https://www.dentons.com/en/insights",
        "linkedin_slug": "dentons",
        "hq": "Toronto",
        "alt_names": ["Dentons"],
    },
    {
        "id": "cassels",
        "name": "Cassels Brock & Blackwell LLP",
        "short": "Cassels",
        "website": "https://www.cassels.com",
        "careers_url": "https://www.cassels.com/careers",
        "news_url": "https://www.cassels.com/insights",
        "linkedin_slug": "cassels-brock-blackwell",
        "hq": "Toronto",
        "alt_names": ["Cassels Brock", "Cassels"],
    },
    {
        "id": "mcmillan",
        "name": "McMillan LLP",
        "short": "McMillan",
        "website": "https://www.mcmillan.ca",
        "careers_url": "https://www.mcmillan.ca/Careers",
        "news_url": "https://www.mcmillan.ca/insights",
        "linkedin_slug": "mcmillan-llp",
        "hq": "Toronto",
        "alt_names": ["McMillan"],
    },
    {
        "id": "gowling",
        "name": "Gowling WLG",
        "short": "Gowling",
        "website": "https://gowlingwlg.com/en/canada",
        "careers_url": "https://gowlingwlg.com/en/careers",
        "news_url": "https://gowlingwlg.com/en/insights-resources",
        "linkedin_slug": "gowling-wlg",
        "hq": "Ottawa",
        "alt_names": ["Gowling WLG", "Gowlings"],
    },
    # ── TIER 3 — Regional / Boutique ────────────────────────────────────
    {
        "id": "aird",
        "name": "Aird & Berlis LLP",
        "short": "Aird & Berlis",
        "website": "https://www.airdberlis.com",
        "careers_url": "https://www.airdberlis.com/careers",
        "news_url": "https://www.airdberlis.com/insights",
        "linkedin_slug": "aird-berlis-llp",
        "hq": "Toronto",
        "alt_names": ["Aird Berlis", "A&B"],
    },
    {
        "id": "miller",
        "name": "Miller Thomson LLP",
        "short": "Miller Thomson",
        "website": "https://www.millerthomson.com",
        "careers_url": "https://www.millerthomson.com/en/careers",
        "news_url": "https://www.millerthomson.com/en/publications",
        "linkedin_slug": "miller-thomson-llp",
        "hq": "Toronto",
        "alt_names": ["Miller Thomson"],
    },
    {
        "id": "fogler",
        "name": "Fogler, Rubinoff LLP",
        "short": "Fogler",
        "website": "https://www.foglers.com",
        "careers_url": "https://www.foglers.com/careers",
        "news_url": "https://www.foglers.com/news",
        "linkedin_slug": "fogler-rubinoff",
        "hq": "Toronto",
        "alt_names": ["Fogler Rubinoff", "Foglers"],
    },
    {
        "id": "weirfoulds",
        "name": "WeirFoulds LLP",
        "short": "WeirFoulds",
        "website": "https://www.weirfoulds.com",
        "careers_url": "https://www.weirfoulds.com/careers",
        "news_url": "https://www.weirfoulds.com/insights",
        "linkedin_slug": "weirfoulds-llp",
        "hq": "Toronto",
        "alt_names": ["WeirFoulds"],
    },
    {
        "id": "torkin",
        "name": "Torkin Manes LLP",
        "short": "Torkin Manes",
        "website": "https://www.torkinmanes.com",
        "careers_url": "https://www.torkinmanes.com/careers",
        "news_url": "https://www.torkinmanes.com/resources",
        "linkedin_slug": "torkin-manes-llp",
        "hq": "Toronto",
        "alt_names": ["Torkin"],
    },
    {
        "id": "loopstra",
        "name": "Loopstra Nixon LLP",
        "short": "Loopstra Nixon",
        "website": "https://www.loopstranixon.com",
        "careers_url": "https://www.loopstranixon.com/careers",
        "news_url": "https://www.loopstranixon.com/news",
        "linkedin_slug": "loopstra-nixon",
        "hq": "Toronto",
        "alt_names": ["Loopstra"],
    },
    {
        "id": "minden",
        "name": "Minden Gross LLP",
        "short": "Minden Gross",
        "website": "https://www.mindengross.com",
        "careers_url": "https://www.mindengross.com/careers",
        "news_url": "https://www.mindengross.com/client-resources",
        "linkedin_slug": "minden-gross-llp",
        "hq": "Toronto",
        "alt_names": ["Minden"],
    },
    {
        "id": "bdp",
        "name": "Burnet, Duckworth & Palmer LLP",
        "short": "BD&P",
        "website": "https://www.bdplaw.com",
        "careers_url": "https://www.bdplaw.com/careers",
        "news_url": "https://www.bdplaw.com/publications",
        "linkedin_slug": "burnet-duckworth-palmer",
        "hq": "Calgary",
        "alt_names": ["BD&P", "Burnet Duckworth"],
    },
    {
        "id": "lawson",
        "name": "Lawson Lundell LLP",
        "short": "Lawson Lundell",
        "website": "https://www.lawsonlundell.com",
        "careers_url": "https://www.lawsonlundell.com/careers",
        "news_url": "https://www.lawsonlundell.com/insights",
        "linkedin_slug": "lawson-lundell-llp",
        "hq": "Vancouver",
        "alt_names": ["Lawson"],
    },
    {
        "id": "mcinnes",
        "name": "McInnes Cooper",
        "short": "McInnes Cooper",
        "website": "https://www.mcinnescooper.com",
        "careers_url": "https://www.mcinnescooper.com/careers",
        "news_url": "https://www.mcinnescooper.com/publications",
        "linkedin_slug": "mcinnes-cooper",
        "hq": "Halifax",
        "alt_names": ["McInnes"],
    },
    {
        "id": "stewartmck",
        "name": "Stewart McKelvey",
        "short": "Stewart McKelvey",
        "website": "https://www.stewartmckelvey.com",
        "careers_url": "https://www.stewartmckelvey.com/careers",
        "news_url": "https://www.stewartmckelvey.com/insights",
        "linkedin_slug": "stewart-mckelvey",
        "hq": "Halifax",
        "alt_names": ["Stewart McKelvey"],
    },
]

FIRMS_BY_ID = {f["id"]: f for f in FIRMS}
