"""
Dashboard generator — produces docs/index.html
A static single-file dashboard showing signals and alerts.
"""

import json
import logging
import os
from datetime import datetime, timezone, timedelta

logger = logging.getLogger("dashboard")


class DashboardGenerator:
    def __init__(self, db, output_path: str = "docs/index.html"):
        self.db = db
        self.output_path = output_path

    def generate(self):
        os.makedirs(os.path.dirname(self.output_path), exist_ok=True)

        signals = self.db.get_signals_this_week()
        # Pull recent alerts from weekly_scores
        scores = self.db.conn.execute(
            "SELECT * FROM weekly_scores ORDER BY score DESC LIMIT 50"
        ).fetchall()

        html = self._render(signals, [dict(r) for r in scores])
        with open(self.output_path, "w", encoding="utf-8") as f:
            f.write(html)

        logger.info(f"Dashboard → {self.output_path} ({len(signals)} signals, {len(scores)} alerts)")

    def _render(self, signals: list[dict], scores: list[dict]) -> str:
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        # Build per-firm summaries
        from collections import defaultdict, Counter
        firm_scores = defaultdict(lambda: {"score": 0, "signals": 0, "departments": Counter()})
        for row in scores:
            fid = row["firm_id"]
            firm_scores[fid]["name"] = row["firm_name"]
            firm_scores[fid]["score"] += row["score"]
            firm_scores[fid]["signals"] += row["signal_count"]
            firm_scores[fid]["departments"][row["department"]] += 1

        # Top firms sorted by score
        top_firms = sorted(firm_scores.items(), key=lambda x: x[1]["score"], reverse=True)[:10]

        # Recent signals table
        recent = signals[:30]

        rows_firms = ""
        for rank, (fid, data) in enumerate(top_firms, 1):
            top_depts = ", ".join(d for d, _ in data["departments"].most_common(3))
            rows_firms += (
                f"<tr><td>{rank}</td><td>{data.get('name','')}</td>"
                f"<td>{data['score']:.1f}</td><td>{data['signals']}</td>"
                f"<td>{top_depts}</td></tr>\n"
            )

        rows_signals = ""
        for s in recent:
            url = s.get("url", "")
            title = s.get("title", "")[:80]
            linked = f'<a href="{url}" target="_blank">{title}</a>' if url else title
            rows_signals += (
                f"<tr><td>{s.get('scraped_at','')[:10]}</td>"
                f"<td>{s.get('firm_name','')}</td>"
                f"<td>{s.get('signal_type','')}</td>"
                f"<td>{s.get('department','')}</td>"
                f"<td>{linked}</td></tr>\n"
            )

        dash_url = os.getenv("DASHBOARD_URL", "#")

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Law Firm Expansion Tracker</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
          background: #0f1117; color: #e2e8f0; margin: 0; padding: 24px; }}
  h1 {{ color: #fff; margin-bottom: 4px; }}
  .sub {{ color: #94a3b8; font-size: 0.85rem; margin-bottom: 32px; }}
  .card {{ background: #1e2433; border-radius: 12px; padding: 24px;
           margin-bottom: 24px; border: 1px solid #2d3748; }}
  h2 {{ color: #7dd3fc; margin-top: 0; font-size: 1rem; text-transform: uppercase;
        letter-spacing: 0.05em; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.82rem; }}
  th {{ text-align: left; color: #94a3b8; border-bottom: 1px solid #2d3748;
        padding: 6px 8px; font-weight: 600; }}
  td {{ padding: 6px 8px; border-bottom: 1px solid #1a2035; }}
  tr:hover td {{ background: #263042; }}
  a {{ color: #7dd3fc; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  .badge {{ background: #1d4ed8; color: #bfdbfe; padding: 2px 8px;
            border-radius: 12px; font-size: 0.75rem; }}
</style>
</head>
<body>
<h1>🏛 Law Firm Expansion Tracker</h1>
<div class="sub">Last updated: {now} &nbsp;·&nbsp;
  {len(signals)} signals (21-day window) &nbsp;·&nbsp;
  {len(scores)} scored alerts</div>

<div class="card">
  <h2>🔥 Top Expanding Firms</h2>
  <table>
    <tr><th>#</th><th>Firm</th><th>Score</th><th>Signals</th><th>Hot Departments</th></tr>
    {rows_firms or "<tr><td colspan=5>No data yet.</td></tr>"}
  </table>
</div>

<div class="card">
  <h2>📡 Recent Signals</h2>
  <table>
    <tr><th>Date</th><th>Firm</th><th>Type</th><th>Department</th><th>Title</th></tr>
    {rows_signals or "<tr><td colspan=5>No signals yet.</td></tr>"}
  </table>
</div>

<div class="sub" style="margin-top:32px;">
  Auto-generated by
  <a href="https://github.com">Law Firm Expansion Tracker</a>.
  Runs daily at 07:00 UTC.
</div>
</body>
</html>"""
